---
- name: Listen for events
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: '{{ dt_url }}'
        dt_api_token: '{{ dt_token }}'
        delay: 15
        # (Default is 1 min) i.e plugin runs every 1 minute
  rules:
    - name: Problem payload Dynatrace for App Failure rate increase issue
      condition: event.payload.eventData["event.status"] is match ("ACTIVE") and event.payload.eventData["event.name"] is match ("Failure rate increase")
      actions:
        - run_job_template:
            name: Dynatrace Easy Travel demo fix
            organization: Default
            job_args:
              extra_vars:
                dt_api_token: '{{ dt_token }}'
                dt_api_url: '{{ dt_url }}'
    - name: Problem payload Dynatrace for App Failure rate increase issue JS
      condition: event.payload.eventData["event.status"] is match ("ACTIVE") and event.payload.eventData["event.name"] is match ("JavaScript error rate increase")
      actions:
        - run_job_template:
            name: Dynatrace Easy Travel demo fix
            organization: Default
            job_args:
              extra_vars:
                dt_api_token: '{{ dt_token }}'
                dt_api_url: '{{ dt_url }}'
    - name: show me the raw event
      condition: true
      actions:
        - print_event:
        - debug:
            msg: "{{ event }}"
